# ansible-playbook play.yml
- hosts: all
  # become global:
  become: yes
  tasks:
    - package:
        name: git
        state: present
    - name: On s'assure de ping les machines
      ping:
    - name: On s'assure d'avoir git présent
      #when: ansible_os_family == 'Debian'
      ignore_errors: yes
      apt:
        name: git
        state: present
    - name: On s'assure que Apache soit installé
      become: yes
      package:
        name: "{{ server }}"
        state: present
    - name: On s'assure que nano soit installé
      package:
        name: nano
        state: present