- hosts: all
  become: yes
  vars:
    mysql_root_password: 1234
    mysql_databases:
      - name: products
      - name: users
    #affiche_bienvenue: hello world
    affiche_dns: blablabla
  roles:
    - my-custom-motd
    #- geerlingguy.mysql